# Generated by Django 6.0.3 on 2026-04-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(max_length=20)),
                ("ects", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(blank=True, upload_to="ucs/")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
