# Generated by Django 6.0.3 on 2026-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("foto", models.ImageField(blank=True, upload_to="docentes/")),
                ("pagina_lusofona", models.URLField()),
                ("unidades", models.ManyToManyField(to="portfolio.unidadecurricular")),
            ],
        ),
    ]
