# Generated by Django 6.0.3 on 2026-04-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_docente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("logo", models.ImageField(blank=True, upload_to="tecnologias/")),
                ("website", models.URLField()),
                ("nivel_interesse", models.IntegerField()),
            ],
        ),
    ]
