# Generated by Django 6.0.3 on 2026-04-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("conceitos", models.TextField()),
                ("imagem", models.ImageField(blank=True, upload_to="projetos/")),
                ("github", models.URLField(blank=True)),
                ("data", models.DateField()),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
