# Generated by Django 6.0.3 on 2026-04-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("nivel", models.IntegerField()),
                ("projetos", models.ManyToManyField(to="portfolio.projeto")),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
            ],
        ),
    ]
