# Generated by Django 6.0.3 on 2026-04-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_makingof"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("descricao", models.TextField()),
                ("interesse", models.IntegerField()),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
            ],
        ),
    ]
