# Generated by Django 6.0.3 on 2026-04-06 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_tfc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docente",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="imagem",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="imagem",
        ),
        migrations.RemoveField(
            model_name="tecnologia",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="imagem",
        ),
        migrations.AlterField(
            model_name="competencia",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="nivel",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="projetos",
            field=models.ManyToManyField(blank=True, to="portfolio.projeto"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="docente",
            name="pagina_lusofona",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="docente",
            name="unidades",
            field=models.ManyToManyField(blank=True, to="portfolio.unidadecurricular"),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="entidade",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="ano_inicio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="conceitos",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="data",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="nivel_interesse",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="interesse",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
