# Generated by Django 6.0.3 on 2026-04-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_remove_docente_foto_remove_makingof_imagem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SobreMim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("biografia", models.TextField()),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("objetivo_profissional", models.TextField(blank=True)),
            ],
        ),
    ]
