# Generated by Django 6.0.3 on 2026-04-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_sobremim"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.projeto",
            ),
        ),
    ]
