# Generated by Django 6.0.3 on 2026-04-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_makingof_projeto"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="ano",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
