# Generated by Django 6.0.3 on 2026-04-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_unidadecurricular_ano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="ano",
            field=models.IntegerField(null=True),
        ),
    ]
